### ISSUE TITLE
I do not like bananas

### ISSUE THREAD

**Issue by jordonbiondo** [Fuco1/banana.el#1]

**Comment by Fuco1** [comment]
Lemme just clarify something: you are a mmmmm person who doesn't like mmmmmm bananas?

**Comment by jordonbiondo** [comment]
Right.

**Comment by Fuco1** [comment]
![Mooooooon](http://upload.wikimedia.org/wikipedia/commons/c/c4/From_the_Earth_to_the_Moon_Jules_Verne.jpg)

(ps: if this is not what you expected I think I'm not getting it :D)
